version: '1.0'

services:
  app:
    image: consol-crud-java
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/consol
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ''
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: consol
      MYSQL_INITDB_SKIP_TZ_CHECK: "true"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

