name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches: [feat/endpoints]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Atualização do código
      uses: actions/checkout@v4

    - name: Definindo a versão da JDK 
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle' 
        java-version: '17'

    - name: Build com Maven
      run: mvn -B package -DskipTests

    - name: listagem teste1
      run: ls ./target/

    - name: Gerar artefato Github com o .jar gerado
      uses: actions/upload-artifact@v4
      with:
        name: aplicacao
        path: ./target/*.jar 

    - name: listagem teste2
      run: ls ./target/

    - name: Gerar artefato Github com os arquivos .sh
      uses: actions/upload-artifact@v4        
      with:
        name: scripts 
        path: .github/scripts/*.sh

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
    - name: Recuperar jars
      uses: actions/download-artifact@v4 
      with:
        name: aplicacao
        path: ./aplicacao/

    - name: Verificar conteúdo do diretório aplicacao
      run: ls -la ./aplicacao/

    - name: Recuperar scripts
      uses: actions/download-artifact@v4
      with:
        name: scripts
        path: ./scripts/

    - name: Verificar conteúdo do diretório scripts
      run: ls -la ./scripts/
