name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches: #branch 'alvo'. Ou seja, se algo mudar nela, a mínima mudança que seja, este arquivo de workflow será executado
      - caioarnonii-patch-3

jobs: # cada 'job' é um agrupamento de steps
  build: # primeiro grupo de steps
    runs-on: ubuntu-latest # aqui apenas indicamos onde o workflow será executado (em qual tipo de VM). No caso indicamos que será num ubuntu. Isso NÃO tem relação com o SO de sua EC2!

    steps: # cada 'step' é uma ação dentro de um grupo de steps
    - name: Atualização do código
      uses: actions/checkout@v2 # action que leva para a VM de execução do workflow os arquivos da branch alvo
      
    - name: Definindo a versão da JDK 
      uses: actions/setup-java@v2 # configura na VM uma versão do Java
      with:
        distribution: 'temurin' # ver opções em https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
        java-version: '17'

    - name: Build com Maven
      run: mvn -B package -DskipTests
