name: GitHub Actions Backend com Deploy na EC2

on:
  push:
    branches:
      - caioarnonii-patch-3

jobs:
  verify-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List directory
        run: ls -a

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verify and build project (Skip tests)
        run: |
          mvn clean verify -DskipTests
          mvn package -DskipTests

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/*.jar

  create-release:
    needs: verify-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Get the latest release tag number
        id: get_release
        run: |
          EXISTING_TAGS=$(curl --silent \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/tags" | jq -r '.[].name')

          MAX_TAG=0
          for TAG in $EXISTING_TAGS; do
            TAG_NUMBER=$(echo "$TAG" | sed 's/[^0-9]*//g')
            if [ "$TAG_NUMBER" -gt "$MAX_TAG" ]; then
              MAX_TAG=$TAG_NUMBER
            fi
          done
          NEXT_TAG=$((MAX_TAG + 1))
          echo "Next release version: v$NEXT_TAG"
          echo "TAG_NAME=v$NEXT_TAG" >> $GITHUB_ENV

      - name: List directory 2
        run: ls -a

      - name: Create a new release
        run: |
          gh release create "$TAG_NAME" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${TAG_NAME#v}" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Upload backend.jar
        run: |
          gh release upload "$TAG_NAME" ./backend.jar \
            --repo="$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  deploy:
    needs: verify-and-build
    runs-on: ubuntu-latest
    
    steps:
      - name: Recuperar artefato
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./

      - name: Recuperar docker-scripts
        uses: actions/download-artifact@v4
        with:
          name: docker-scripts
          path: ./docker-scripts/

      - name: Enviar o JAR p/ a EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.ACCESS_WEBSERVER_KEY }}
          source: ./*.jar
          target: /home/ubuntu/deploy-api/

      - name: Enviar os docker-scripts p/ a EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.ACCESS_WEBSERVER_KEY }}
          source: ./docker-scripts/*
          target: /home/ubuntu/deploy-api/

      - name: Criar arquivo .pem a partir da variável ACCESS_WEBSERVER_KEY e fazer o chmod 400 nele
        id: geracao-arquivo-pem
        run: |
          echo "${{ secrets.ACCESS_WEBSERVER_KEY }}" >> $HOME/deploy_key.pem
          chmod 400 $HOME/deploy_key.pem

      - name: Conectar via SSH à EC2 privada para implantar e reiniciar a API
        run: |
          ssh -T -o StrictHostKeyChecking=no -i $HOME/deploy_key.pem ubuntu@${{ secrets.DEPLOY_HOST }} << 'EOF'
          echo "${{ secrets.ACCESS_WEBSERVER_KEY }}" >> $HOME/deploy_key.pem
          chmod 400 $HOME/deploy_key.pem
          scp -i $HOME/deploy_key.pem deploy-api/backend.jar ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu/deploy-api/
          scp -i $HOME/deploy_key.pem deploy-api/docker-scripts/* ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu/deploy-api/
          ssh -i $HOME/deploy_key.pem ubuntu@${{ secrets.IP_PRIVADO_EC2 }} "sudo docker-compose -f /home/ubuntu/deploy-api/docker-compose.yml up -d --build"
          EOF
